[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600
monitor_filters = esp32_exception_decoder

board_build.partitions = default.csv

; ---------- Serial Upload ----------
;upload_port = 192.168.1.2

; ---------- OTA Upload ----------
;upload_protocol = espota

lib_deps =
    adafruit/Adafruit NeoPixel
    bblanchon/ArduinoJson
    tzapu/WiFiManager
    knolleary/PubSubClient
    https://github.com/BoschSensortec/BSEC-Arduino-library

build_flags =
    -DCORE_DEBUG_LEVEL=3